version: '2'

services:
  php70:
    image: connectivdocker/php:7.0
    container_name: php70
    networks:
      internal:
    links:
      - mysql
    volumes:
      - ./example:/var/www/html/example.com
    restart: always

  php71:
    image: connectivdocker/php:7.1
    container_name: php71
    networks:
      internal:
    links:
      - mysql
    volumes:
      - ./example:/var/www/html/example71.com
    restart: always

  php72:
    image: connectivdocker/php:7.2
    container_name: php72
    networks:
      internal:
    links:
      - mysql
    volumes:
      - ./example:/var/www/html/example72.com
    restart: always

  httpd:
    image: httpd:2.4.33-alpine
    container_name: httpd
    networks:
      internal:
        ipv4_address: 172.30.0.89
    volumes:
      - ./docker/httpd-alpine/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/httpd-alpine/conf/virtual-hosts:/usr/local/apache2/conf/extra/vhosts
      - ./docker/httpd-alpine/conf/ssl:/usr/local/apache2/ssl
      - ./docker/logs/httpd:/var/log/httpd
    links:
      - php70
      - php71
      - php72
    volumes_from:
      - php70
      - php71
      - php72
    restart: always

  mysql:
    image: connectivdocker/mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker
    networks:
      internal:
        ipv4_address: 172.30.0.3
    volumes:
      - ./docker/database:/var/lib/mysql
    restart: always

networks:
  internal:
    ipam:
      config:
      - subnet: 172.30.0.0/16
