version: '2'

services:
  php70:
    image: connectivdocker/laravel-docker-php70
    container_name: php70
    networks:
      internal:
        ipv4_address: 172.30.0.70
    links:
    - mysql
    volumes:
    - ./blog:/var/www/html/blog.com
    restart: always

  php71:
    image: connectivdocker/laravel-docker-php71
    container_name: php71
    networks:
      internal:
        ipv4_address: 172.30.0.71
    links:
    - mysql
    volumes:
    - ./blog:/var/www/html/blog.com
    restart: always

  httpd:
    image: connectivdocker/laravel-docker-httpd
    container_name: httpd
    networks:
      internal:
        ipv4_address: 172.30.0.89
    ports:
    - '80:80'
    - '443:443'
    volumes:
    - ./docker/httpd-alpine/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    - ./docker/httpd-alpine/conf/virtual-hosts:/usr/local/apache2/conf/extra/vhosts
    - ./docker/httpd-alpine/conf/ssl:/usr/local/apache2/ssl
    - ./docker/logs/httpd:/var/log/httpd
    links:
      - php70
      - php71
    volumes_from:
      - php70
      - php71
    restart: always

  mysql:
    image: connectivdocker/laravel-mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker
    networks:
      internal:
        ipv4_address: 172.33.0.3
    volumes:
    - ./docker/database:/var/lib/mysql
    restart: always

networks:
  internal:
    ipam:
      config:
      - subnet: 172.30.0.0/16
